[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "CounterSocial User Guide"
authors = [{name = "CounterSocial", email = "support@counter.social"}]
dynamic = ["version", "description"]
